### ISSUE TITLE
`dashwallet send` doesn't work with raw addresses

### ISSUE THREAD

**Issue by coolaj86** [dashhive/dashwallet-cli#3]
Looks like addresses that don't exist in the wallet as an xpub index fail to send:

```sh
dashwallet send XgnPqzmC7v3aVDyLjTqMcz6PDcgkVWo4xi Xd9z1sxXh
```

```
🚜 DASH_ENV=dev2
⚙️ ~/.config/dash.dev2/

Fail:
TypeError: Cannot set properties of undefined (setting 'sync_at')
    at wallet._authDirtyTx (/Users/aj/.local/opt/node-v18.15.0/lib/node_modules/dashwallet-cli/node_modules/dashwallet/dashwallet.js:1025:49)
    at wallet.createDirtyTx (/Users/aj/.local/opt/node-v18.15.0/lib/node_modules/dashwallet-cli/node_modules/dashwallet/dashwallet.js:977:20)
    at async pay (/Users/aj/.local/opt/node-v18.15.0/lib/node_modules/dashwallet-cli/bin/dashwallet.js:680:15)
    at async main (/Users/aj/.local/opt/node-v18.15.0/lib/node_modules/dashwallet-cli/bin/dashwallet.js:188:5)
```

**Comment by coolaj86** [comment]
Fixed in v0.6.x
