### ISSUE TITLE
`dashwallet contact main` causes cache / indexing issues

### ISSUE THREAD

**Issue by coolaj86** [dashhive/dashwallet-cli#4]
# Update

DO NOT do this (normally you wouldn't):

```sh
dashwallet contact main
```

Because `main` is special (private wallet at index 0) and contacts are expected to have the private wallet at index 1, and the `hdpath` is associated with the wallet, but not the wallet's private key index (for which it is expected there will only ever be one)... mismatch stuff happens.

No money is lost, but we need the index information saved with the caches so that we can recover the _correct_ Private Key at the correct index and spend the coin rather than just look at how pretty it is.

# Original

I was messing around between 3 different wallets and... something went wrong. Looks like either the `hdpath` really is generating the wrong address (unlikely) or maybe I added the XPub incorrectly on one and then it failed to associate a particular address with the correct account.

```sh
dashwallet send @kaspars-test 0.10001000
```

```text
🚜 DASH_ENV=dev
⚙️ ~/.config/dash.dev/

Fail:
Error: check fail: hdpath 'm/44'/5'/0'/1/0' for 'XwoVnbLf8nQ4dQsjo9SULeCqH7BTxarQGD' derived 'Xgv3dn8rwJYZYKNeLhQvss9EGbPGw83VcE'
    at wallet._findWif (/Users/aj/.local/opt/node-v18.15.0/lib/node_modules/dashwallet-cli/node_modules/dashwallet/dashwallet.js:1410:15)
    at async wallet.findWif (/Users/aj/.local/opt/node-v18.15.0/lib/node_modules/dashwallet-cli/node_modules/dashwallet/dashwallet.js:1348:21)
    at async /Users/aj/.local/opt/node-v18.15.0/lib/node_modules/dashwallet-cli/node_modules/dashwallet/dashwallet.js:1316:23
    at async wallet._utxosToPrivKeys (/Users/aj/.local/opt/node-v18.15.0/lib/node_modules/dashwallet-cli/node_modules/dashwallet/dashwallet.js:1313:7)
    at async wallet.createDirtyTx (/Users/aj/.local/opt/node-v18.15.0/lib/node_modules/dashwallet-cli/node_modules/dashwallet/dashwallet.js:955:18)
    at async pay (/Users/aj/.local/opt/node-v18.15.0/lib/node_modules/dashwallet-cli/bin/dashwallet.js:680:15)
    at async main (/Users/aj/.local/opt/node-v18.15.0/lib/node_modules/dashwallet-cli/bin/dashwallet.js:188:5)
```

**Comment by coolaj86** [comment]
The problem is this:

Normally `dashwallet contact @johndoe` will create a private wallet named `johndoe:1`, and there will be only one of it, and it will have the `contact` of `@johndoe`.

`main` is a very special case. If you try to `dashwallet contact main`, which is already the literal name `main`, it will create `main:1`.

Since the 0-index of a contact is the XPub, and the 1-index is the Private Key, and this is NOT the scheme used for main, thing got tangled.

```js
{
  "main": {
    "name": "main",
    "label": "main",
    "device": null,
    "contact": null, // <===========
    "priority": 0,
    "phrase": "zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo wrong", // <===== contacts' 0 don't have private keys
    "wifs": [],
    "created_at": "2020-01-01T01:01:01.000Z",
    "archived_at": null
  }
  "main:1": { // <===== 1-index DOES have private key
    "name": "main",
    "label": "main",
    "device": null,
    "contact": "main", // <===========
    "priority": 0,
    "phrase": "cat swing flag economy stadium alone churn speed unique patch report train", // contacts 1 DO have private keys
    "wifs": [],
    "created_at": "2020-01-01T01:01:01.000Z",
    "archived_at": null
  }
}
```

**Comment by coolaj86** [comment]
Solution: Treat `main` as special (along with `savings` and `wifs`) and don't allow it to be used as a contact. In v0.6.x
